### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tetsunokishi** [Asthriona/Yukiko#173] opened 2020-10-31 08:36 UTC
Help me plase
![Безымянный](https://user-images.githubusercontent.com/72111329/97774954-48b2e180-1b6d-11eb-9bcc-c2463e2960b4.png)

**Comment by Asthriona** [comment] 2020-10-31 08:48
hi,
please send us your botcinfig.json.

**Comment by Tetsunokishi** [comment] 2020-10-31 09:10
@Asthriona 
{
    "token": "************************************************",
    "prefix": "!",
    "YtKey": "***************************************************",
    "dbLink": "mongodb+srv://bot1:PASS@cluster0.1emtj.mongodb.net/bot1?retryWrites=true&w=majority",
}

**Comment by Heazher** [comment] 2020-10-31 11:10
can you try removing the last commas after your database link? 
json don't take commas on the last line. I know the exemple have it, I'm going to fix that right now.

**Comment by Tetsunokishi** [comment] 2020-10-31 11:13
@Heazher 
![Безымянный](https://user-images.githubusercontent.com/72111329/97777737-3b085680-1b83-11eb-8d54-27e35c05623e.png)

**Comment by Heazher** [comment] 2020-10-31 11:19
@ENOT1KK oh, for a second I thought we forgot to save that package, but it's in our [package.json](https://github.com/Asthriona/Yukiko/blob/28039da1495dd5558ae284ff2aba8ba8674a271c/package.json#L35)
did you execute the command `npm  install` ?
I'm sadly unable to test the code on my Windows computer at the moment, because of an update.

**Comment by Tetsunokishi** [comment] 2020-10-31 11:24
@Heazher 
{
"token": "",
"prefix": "!",
"YtKey": "***",
"dbLink": "mongodb+srv://bot1:PASS@cluster0.1emtj.mongodb.net/bot1?retryWrites=true&w=majority"
}
![Безымянный](https://user-images.githubusercontent.com/72111329/97777955-bc141d80-1b84-11eb-80a7-ee58c63e155e.png)

**Comment by Heazher** [comment] 2020-10-31 11:32
@ENOT1KK you are missing a package here. but I'm unable to see wich one. 
again did you typed the command `npm install`?

**Comment by Tetsunokishi** [comment] 2020-10-31 11:42
@Heazher Yes, I installed all the packages.

**Comment by Heazher** [comment] 2020-10-31 11:55
Well apparently something went wrong. because you are missing few packages, and we will be unable to help you without more information than half part of your logs in a screenshot.
and since this error is not from us or our code we can hardly help you. 
if you followed the instruction in our [README.md](https://github.com/Asthriona/Yukiko#for-windows) everything should work fine.
again I regret that your issue goes beyond our support. plus This project is now Unsupported until the release of Yukiko 2.0 ([click more information](https://gist.github.com/Asthriona/660cc6635409f1e9bf3294c38561f91c))
_*Please note that if you have modified the code we will not be able to help you._
as alternative you can use Our production version of Yukiko at [Yukiko.app](https://yukiko.app)

as for testing, I just clone the repo did all the setup is you may have done and everything work as intended. so we are unable to reproduce the error.

```
> yukiko@2.0.0 dev C:\Users\麗清\Desktop\issue\Yukiko
> nodemon start

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node start index.js`
.------------------------------.
|           Commands           |
|------------------------------|
|    Command     | Load status |
|----------------|-------------|
| eval.js        | ✔️ Ok！      |
| update.js      | ✔️ Ok！      |
| addcard.js     | ✔️ Ok！      |
| botInfo.js     | ✔️ Ok！      |
| game.js        | ✔️ Ok！      |
| help.js        | ✔️ Ok！      |
| host.js        | ✔️ Ok！      |
| invit.js       | ✔️ Ok！      |
| lbtop10.js     | ✔️ Ok！      |
| leaderboard.js | ✔️ Ok！      |
| ping.js        | ✔️ Ok！      |
| rank.js        | ✔️ Ok！      |
| reddit.js      | ✔️ Ok！      |
| serverinfo.js  | ✔️ Ok！      |
| uptime.js      | ✔️ Ok！      |
| whois.js       | ✔️ Ok！      |
| wink.js        | ✔️ Ok！      |
| wow.js         | ✔️ Ok！      |
| ban.js         | ✔️ Ok！      |
| clear.js       | ✔️ Ok！      |
| createrole.js  | ✔️ Ok！      |
| forceskip.js   | ✔️ Ok！      |
| kick.js        | ✔️ Ok！      |
| mute.js        | ✔️ Ok！      |
| report.js      | ✔️ Ok！      |
| say.js         | ✔️ Ok！      |
| unwarn.js      | ✔️ Ok！      |
| warns.js       | ✔️ Ok！      |
| animefm.js     | ✔️ Ok！      |
| leave.js       | ✔️ Ok！      |
| pause.js       | ✔️ Ok！      |
| play.js        | ✔️ Ok！      |
| queue.js       | ✔️ Ok！      |
| resume.js      | ✔️ Ok！      |
| search.js      | ✔️ Ok！      |
| skip.js        | ✔️ Ok！      |
| volume.js      | ✔️ Ok！      |
'------------------------------'
Setting bot presence...
YukikoDB: connected to 212.47.226.149
Rise Dev is now started and running in undefined environement!
```

Thanks for your patience

**Comment by Asthriona** [comment] 2020-11-09 10:30
Closing now.

**Closed as completed by Asthriona** 2020-11-09 10:30 UTC
Labels: Error
